from sqlinpython import functions as f
from sqlinpython.expression import Expression


def to_str(element: Expression) -> str:
    buffer: list[str] = []
    element._create_query(buffer)
    return "".join(buffer)


# Core functions
def test_core_functions() -> None:
    assert to_str(f.Abs(1)) == "ABS(1)"
    assert to_str(f.Changes()) == "CHANGES()"
    assert to_str(f.Char(1, 2, 3, 4)) == "CHAR(1, 2, 3, 4)"
    assert to_str(f.Coalesce(1, 2)) == "COALESCE(1, 2)"
    assert to_str(f.Concat("a")) == "CONCAT('a')"
    assert to_str(f.ConcatWs("_", "a")) == "CONCAT_WS('_', 'a')"
    assert to_str(f.Format(1)) == "FORMAT(1)"
    assert to_str(f.Glob(1, 2)) == "GLOB(1, 2)"
    assert to_str(f.Hex(1)) == "HEX(1)"
    assert to_str(f.If(True, 1)) == "IF(TRUE, 1)"
    assert to_str(f.Ifnull(1, 2)) == "IFNULL(1, 2)"
    assert to_str(f.Iif(1, 2)) == "IIF(1, 2)"
    assert to_str(f.Instr("a", "b")) == "INSTR('a', 'b')"
    assert to_str(f.LastInsertRowid()) == "LAST_INSERT_ROWID()"
    assert to_str(f.Length(1)) == "LENGTH(1)"
    assert to_str(f.Like(1, 2)) == "LIKE(1, 2)"
    assert to_str(f.Like(1, 2, 3)) == "LIKE(1, 2, 3)"
    assert to_str(f.Likelihood(1, 2)) == "LIKELIHOOD(1, 2)"
    assert to_str(f.Likely(1)) == "LIKELY(1)"
    assert to_str(f.LoadExtension(1)) == "LOAD_EXTENSION(1)"
    assert to_str(f.LoadExtension(1, 2)) == "LOAD_EXTENSION(1, 2)"
    assert to_str(f.Lower("a")) == "LOWER('a')"
    assert to_str(f.Ltrim("a")) == "LTRIM('a')"
    assert to_str(f.Ltrim("a", "b")) == "LTRIM('a', 'b')"
    assert to_str(f.Max(1, 2)) == "MAX(1, 2)"
    assert to_str(f.Min(1, 2)) == "MIN(1, 2)"
    assert to_str(f.Nullif(1, 2)) == "NULLIF(1, 2)"
    assert to_str(f.OctetLength(1)) == "OCTET_LENGTH(1)"
    assert to_str(f.Printf("a")) == "PRINTF('a')"
    assert to_str(f.Quote(1)) == "QUOTE(1)"
    assert to_str(f.Random()) == "RANDOM()"
    assert to_str(f.Randomblob(1)) == "RANDOMBLOB(1)"
    assert to_str(f.Replace("a", "b", "c")) == "REPLACE('a', 'b', 'c')"
    assert to_str(f.Round(1)) == "ROUND(1)"
    assert to_str(f.Round(1, 2)) == "ROUND(1, 2)"
    assert to_str(f.Rtrim(1)) == "RTRIM(1)"
    assert to_str(f.Rtrim(1, 2)) == "RTRIM(1, 2)"
    assert to_str(f.Sign(1)) == "SIGN(1)"
    assert to_str(f.Soundex(1)) == "SOUNDEX(1)"
    assert to_str(f.SqliteCompileoptionGet(1)) == "SQLITE_COMPILEOPTION_GET(1)"
    assert to_str(f.SqliteCompileoptionUsed(1)) == "SQLITE_COMPILEOPTION_USED(1)"
    assert to_str(f.SqliteOffset(1)) == "SQLITE_OFFSET(1)"
    assert to_str(f.SqliteSourceId()) == "SQLITE_SOURCE_ID()"
    assert to_str(f.SqliteVersion()) == "SQLITE_VERSION()"
    assert to_str(f.Substr("a", "b")) == "SUBSTR('a', 'b')"
    assert to_str(f.Substr("a", "b", "c")) == "SUBSTR('a', 'b', 'c')"
    assert to_str(f.Substring("a", "b")) == "SUBSTRING('a', 'b')"
    assert to_str(f.Substring("a", "b", "c")) == "SUBSTRING('a', 'b', 'c')"
    assert to_str(f.TotalChanges()) == "TOTAL_CHANGES()"
    assert to_str(f.Trim(1)) == "TRIM(1)"
    assert to_str(f.Trim(1, 2)) == "TRIM(1, 2)"
    assert to_str(f.Typeof(1)) == "TYPEOF(1)"
    assert to_str(f.Unhex(1)) == "UNHEX(1)"
    assert to_str(f.Unhex(1, 2)) == "UNHEX(1, 2)"
    assert to_str(f.Unicode(1)) == "UNICODE(1)"
    assert to_str(f.Unistr(1)) == "UNISTR(1)"
    assert to_str(f.UnistrQuote(1)) == "UNISTR_QUOTE(1)"
    assert to_str(f.Unlikely(1)) == "UNLIKELY(1)"
    assert to_str(f.Upper(1)) == "UPPER(1)"
    assert to_str(f.Zeroblob(1)) == "ZEROBLOB(1)"


def test_aggregate_functions() -> None:
    assert to_str(f.Avg(1)) == "AVG(1)"
    assert to_str(f.Count(1)) == "COUNT(1)"
    assert to_str(f.Count("*")) == "COUNT(*)"
    assert to_str(f.GroupConcat(1)) == "GROUP_CONCAT(1)"
    assert to_str(f.GroupConcat(1, 2)) == "GROUP_CONCAT(1, 2)"
    assert to_str(f.StringAgg(1, 2)) == "STRING_AGG(1, 2)"
    assert to_str(f.Max(1)) == "MAX(1)"
    assert to_str(f.Median(1)) == "MEDIAN(1)"
    assert to_str(f.Min(1)) == "MIN(1)"
    assert to_str(f.Percentile(1, 2)) == "PERCENTILE(1, 2)"
    assert to_str(f.PercentileCont(1, 2)) == "PERCENTILE_CONT(1, 2)"
    assert to_str(f.PercentileDisc(1, 2)) == "PERCENTILE_DISC(1, 2)"
    assert to_str(f.Sum(1)) == "SUM(1)"
    assert to_str(f.Total(1)) == "TOTAL(1)"


def test_window_functions() -> None:
    assert to_str(f.RowNumber()) == "ROW_NUMBER()"
    assert to_str(f.Rank()) == "RANK()"
    assert to_str(f.DenseRank()) == "DENSE_RANK()"
    assert to_str(f.PercentRank()) == "PERCENT_RANK()"
    assert to_str(f.CumeDist()) == "CUME_DIST()"
    assert to_str(f.Ntile(1)) == "NTILE(1)"
    assert to_str(f.Lag(1)) == "LAG(1)"
    assert to_str(f.Lag(1, 2)) == "LAG(1, 2)"
    assert to_str(f.Lag(1, 2, 3)) == "LAG(1, 2, 3)"
    assert to_str(f.Lead(1)) == "LEAD(1)"
    assert to_str(f.Lead(1, 2)) == "LEAD(1, 2)"
    assert to_str(f.Lead(1, 2, 3)) == "LEAD(1, 2, 3)"
    assert to_str(f.FirstValue(1)) == "FIRST_VALUE(1)"
    assert to_str(f.LastValue(1)) == "LAST_VALUE(1)"
    assert to_str(f.NthValue(1, 2)) == "NTH_VALUE(1, 2)"


def test_time_functions() -> None:
    assert to_str(f.Date("t")) == "DATE('t')"
    assert to_str(f.Time("t")) == "TIME('t')"
    assert to_str(f.Datetime("t")) == "DATETIME('t')"
    assert to_str(f.Julianday("t")) == "JULIANDAY('t')"
    assert to_str(f.Unixepoch("t")) == "UNIXEPOCH('t')"
    assert to_str(f.Strftime("f", "t")) == "STRFTIME('f', 't')"
    assert to_str(f.Timediff("t1", "t2")) == "TIMEDIFF('t1', 't2')"


# Math functions
def test_math_functions() -> None:
    assert to_str(f.Acos(1)) == "ACOS(1)"
    assert to_str(f.Acosh(1)) == "ACOSH(1)"
    assert to_str(f.Asin(1)) == "ASIN(1)"
    assert to_str(f.Asinh(1)) == "ASINH(1)"
    assert to_str(f.Atan(1)) == "ATAN(1)"
    assert to_str(f.Atan2(1, 2)) == "ATAN2(1, 2)"
    assert to_str(f.Atanh(1)) == "ATANH(1)"
    assert to_str(f.Ceil(1)) == "CEIL(1)"
    assert to_str(f.Ceiling(1)) == "CEILING(1)"
    assert to_str(f.Cos(1)) == "COS(1)"
    assert to_str(f.Cosh(1)) == "COSH(1)"
    assert to_str(f.Degrees(1)) == "DEGREES(1)"
    assert to_str(f.Exp(1)) == "EXP(1)"
    assert to_str(f.Floor(1)) == "FLOOR(1)"
    assert to_str(f.Ln(1)) == "LN(1)"
    assert to_str(f.Log(1, 2)) == "LOG(1, 2)"
    assert to_str(f.Log(1)) == "LOG(1)"
    assert to_str(f.Log10(1)) == "LOG10(1)"
    assert to_str(f.Log2(1)) == "LOG2(1)"
    assert to_str(f.Mod(1, 2)) == "MOD(1, 2)"
    assert to_str(f.Pi()) == "PI()"
    assert to_str(f.Pow(1, 2)) == "POW(1, 2)"
    assert to_str(f.Power(1, 2)) == "POWER(1, 2)"
    assert to_str(f.Radians(1)) == "RADIANS(1)"
    assert to_str(f.Sin(1)) == "SIN(1)"
    assert to_str(f.Sinh(1)) == "SINH(1)"
    assert to_str(f.Sqrt(1)) == "SQRT(1)"
    assert to_str(f.Tan(1)) == "TAN(1)"
    assert to_str(f.Tanh(1)) == "TANH(1)"
    assert to_str(f.Trunc(1)) == "TRUNC(1)"


def test_json_scalar_functions() -> None:
    assert to_str(f.Json("j")) == "JSON('j')"
    assert to_str(f.Jsonb("j")) == "JSONB('j')"
    assert to_str(f.JsonArray("v1", "v2")) == "JSON_ARRAY('v1', 'v2')"
    assert to_str(f.JsonbArray("v1", "v2")) == "JSONB_ARRAY('v1', 'v2')"
    assert (
        to_str(f.JsonbArrayInsert("j", "p", "v")) == "JSONB_ARRAY_INSERT('j', 'p', 'v')"
    )
    assert (
        to_str(f.JsonArrayInsert("j", "p", "v")) == "JSON_ARRAY_INSERT('j', 'p', 'v')"
    )
    assert to_str(f.JsonArrayLength("j")) == "JSON_ARRAY_LENGTH('j')"
    assert to_str(f.JsonArrayLength("j", "p")) == "JSON_ARRAY_LENGTH('j', 'p')"
    assert to_str(f.JsonErrorPosition("j")) == "JSON_ERROR_POSITION('j')"
    assert to_str(f.JsonExtract("j", "p")) == "JSON_EXTRACT('j', 'p')"
    assert to_str(f.JsonbExtract("j", "p")) == "JSONB_EXTRACT('j', 'p')"
    assert to_str(f.JsonInsert("j", "p", "v")) == "JSON_INSERT('j', 'p', 'v')"
    assert to_str(f.JsonbInsert("j", "p", "v")) == "JSONB_INSERT('j', 'p', 'v')"
    assert to_str(f.JsonObject("k", "v")) == "JSON_OBJECT('k', 'v')"
    assert to_str(f.JsonbObject("k", "v")) == "JSONB_OBJECT('k', 'v')"
    assert to_str(f.JsonPatch("j1", "j2")) == "JSON_PATCH('j1', 'j2')"
    assert to_str(f.JsonbPatch("j1", "j2")) == "JSONB_PATCH('j1', 'j2')"
    assert to_str(f.JsonPretty("j")) == "JSON_PRETTY('j')"
    assert to_str(f.JsonRemove("j", "p")) == "JSON_REMOVE('j', 'p')"
    assert to_str(f.JsonbRemove("j", "p")) == "JSONB_REMOVE('j', 'p')"
    assert to_str(f.JsonReplace("j", "p", "v")) == "JSON_REPLACE('j', 'p', 'v')"
    assert to_str(f.JsonbReplace("j", "p", "v")) == "JSONB_REPLACE('j', 'p', 'v')"
    assert to_str(f.JsonSet("j", "p", "v")) == "JSON_SET('j', 'p', 'v')"
    assert to_str(f.JsonbSet("j", "p", "v")) == "JSONB_SET('j', 'p', 'v')"
    assert to_str(f.JsonType("j")) == "JSON_TYPE('j')"
    assert to_str(f.JsonType("j", "p")) == "JSON_TYPE('j', 'p')"
    assert to_str(f.JsonValid("j")) == "JSON_VALID('j')"
    assert to_str(f.JsonValid("j", "f")) == "JSON_VALID('j', 'f')"
    assert to_str(f.JsonQuote("v")) == "JSON_QUOTE('v')"


def test_json_aggregate_functions() -> None:
    assert to_str(f.JsonGroupArray("v")) == "JSON_GROUP_ARRAY('v')"
    assert to_str(f.JsonbGroupArray("v")) == "JSONB_GROUP_ARRAY('v')"
    assert to_str(f.JsonGroupObject("l", "v")) == "JSON_GROUP_OBJECT('l', 'v')"
    assert to_str(f.JsonbGroupObject("l", "v")) == "JSONB_GROUP_OBJECT('l', 'v')"
